Repository CHA-CALL/ChaCall-Server, pull requests merged in 2025-09, with the labels that each got.

#6 [feat] 카카오 소셜 로그인 연동 및 인증/인가 필터 도입
  build.gradle
  src/main/java/konkuk/chacall/domain/user/domain/model/Role.java
  src/main/java/konkuk/chacall/domain/user/domain/model/User.java
  src/main/java/konkuk/chacall/domain/user/domain/repository/UserRepository.java
  src/main/java/konkuk/chacall/global/common/exception/JsonParsingException.java
  src/main/java/konkuk/chacall/global/common/exception/code/ErrorCode.java
  src/main/java/konkuk/chacall/global/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/konkuk/chacall/global/common/security/annotation/UserId.java
  src/main/java/konkuk/chacall/global/common/security/constant/AuthParameters.java
  src/main/java/konkuk/chacall/global/common/security/filter/JwtAuthenticationEntryPoint.java
  src/main/java/konkuk/chacall/global/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/CustomOAuth2User.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/CustomOAuth2UserService.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/CustomSuccessHandler.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/KakaoUserDetails.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/LoginUser.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/OAuth2UserDetails.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/auth/AuthController.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/auth/dto/AuthTokenRequest.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/auth/dto/AuthTokenResponse.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/tokenstorage/LoginTokenStorage.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/tokenstorage/RedisLoginTokenStorage.java
  src/main/java/konkuk/chacall/global/common/security/property/ServerWebProperties.java
  src/main/java/konkuk/chacall/global/common/security/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/konkuk/chacall/global/common/security/resolver/UserIdArgumentResolver.java
  src/main/java/konkuk/chacall/global/common/security/util/JwtUtil.java
  src/main/java/konkuk/chacall/global/config/JsonConfig.java
  src/main/java/konkuk/chacall/global/config/RedisConfig.java
  src/main/java/konkuk/chacall/global/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/java/konkuk/chacall/ChacallApplicationTests.java
  src/test/resources/application-test.yml
Labels: 🛠️ feat, 😀 현준

#9 [DOCS] Swagger 명세 추가
  build.gradle
  src/main/java/konkuk/chacall/domain/owner/presentation/OwnerController.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/request/RegisterBankAccountRequest.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/request/UpdateBankAccountRequest.java
  src/main/java/konkuk/chacall/domain/test/TestController.java
  src/main/java/konkuk/chacall/global/common/annotation/ExceptionDescription.java
  src/main/java/konkuk/chacall/global/common/annotation/UserId.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/auth/AuthController.java
  src/main/java/konkuk/chacall/global/common/security/resolver/UserIdArgumentResolver.java
  src/main/java/konkuk/chacall/global/common/swagger/ExampleHolder.java
  src/main/java/konkuk/chacall/global/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/chacall/global/config/OpenApiConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/test/resources/application-test.yml
Labels: 📄 docs, 😀 현준

#10 [FEAT] 사장님 - 자주 쓰는 채팅 CRUD 기능 구현
  src/main/java/konkuk/chacall/domain/owner/application/OwnerService.java
  src/main/java/konkuk/chacall/domain/owner/application/chatTemplate/ChatTemplateService.java
  src/main/java/konkuk/chacall/domain/owner/domain/model/ChatTemplate.java
  src/main/java/konkuk/chacall/domain/owner/domain/repository/ChatTemplateRepository.java
  src/main/java/konkuk/chacall/domain/owner/presentation/OwnerController.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/request/RegisterChatTemplateRequest.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/request/UpdateChatTemplateRequest.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/response/BankAccountResponse.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/response/ChatTemplateResponse.java
  src/main/java/konkuk/chacall/global/common/exception/code/ErrorCode.java
  src/main/java/konkuk/chacall/global/common/security/resolver/UserIdArgumentResolver.java
  src/main/java/konkuk/chacall/global/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/chacall/global/config/SecurityConfig.java
Labels: 🛠️ feat, ☺️ 상균

#13 [FEAT] 사용자 마이페이지 정보 조회/수정 api 구현
  src/main/java/konkuk/chacall/domain/user/application/UserService.java
  src/main/java/konkuk/chacall/domain/user/domain/model/Gender.java
  src/main/java/konkuk/chacall/domain/user/domain/model/User.java
  src/main/java/konkuk/chacall/domain/user/presentation/UserController.java
  src/main/java/konkuk/chacall/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/konkuk/chacall/domain/user/presentation/dto/response/UserResponse.java
  src/main/java/konkuk/chacall/global/common/exception/code/ErrorCode.java
  src/main/java/konkuk/chacall/global/common/security/oauth2/auth/AuthController.java
  src/main/java/konkuk/chacall/global/common/swagger/SwaggerResponseDescription.java
Labels: 🛠️ feat, 😀 현준

#23 [FEAT] 지역 조회 / 검색 API 구현
  src/main/java/konkuk/chacall/domain/foodtruck/domain/FoodTruckServiceArea.java
  src/main/java/konkuk/chacall/domain/region/application/RegionService.java
  src/main/java/konkuk/chacall/domain/region/application/query/RegionQueryService.java
  src/main/java/konkuk/chacall/domain/region/application/search/RegionSearchService.java
  src/main/java/konkuk/chacall/domain/region/domain/model/Region.java
  src/main/java/konkuk/chacall/domain/region/domain/repository/RegionRepository.java
  src/main/java/konkuk/chacall/domain/region/presentation/RegionController.java
  src/main/java/konkuk/chacall/domain/region/presentation/dto/request/RegionQueryRequest.java
  src/main/java/konkuk/chacall/domain/region/presentation/dto/request/RegionSearchRequest.java
  src/main/java/konkuk/chacall/domain/region/presentation/dto/response/RegionResponse.java
  src/main/java/konkuk/chacall/domain/region/presentation/dto/validator/ValidRegionQuery.java
  src/main/java/konkuk/chacall/domain/region/presentation/dto/validator/ValidRegionQueryValidator.java
  src/main/java/konkuk/chacall/global/common/exception/code/ErrorCode.java
  src/main/java/konkuk/chacall/global/common/swagger/SwaggerResponseDescription.java
Labels: 🛠️ feat, ☺️ 상균

#34 [FEAT] 푸드트럭 메뉴 등록/조회 API & 푸드트럭 관련 간단한 CRUD 구현
  src/main/java/konkuk/chacall/domain/foodtruck/application/FoodTruckService.java
  src/main/java/konkuk/chacall/domain/foodtruck/application/command/FoodTruckCommandService.java
  src/main/java/konkuk/chacall/domain/foodtruck/domain/model/FoodTruck.java
  src/main/java/konkuk/chacall/domain/foodtruck/domain/model/Menu.java
  src/main/java/konkuk/chacall/domain/foodtruck/domain/repository/FoodTruckRepository.java
  src/main/java/konkuk/chacall/domain/foodtruck/domain/repository/MenuRepository.java
  src/main/java/konkuk/chacall/domain/foodtruck/domain/repository/infra/FoodTruckSearchRepositoryImpl.java
  src/main/java/konkuk/chacall/domain/foodtruck/domain/value/MenuViewedStatus.java
  src/main/java/konkuk/chacall/domain/foodtruck/presentation/FoodTruckController.java
  src/main/java/konkuk/chacall/domain/foodtruck/presentation/dto/request/FoodTruckNameDuplicateCheckRequest.java
  src/main/java/konkuk/chacall/domain/foodtruck/presentation/dto/response/FoodTruckNameDuplicateCheckResponse.java
  src/main/java/konkuk/chacall/domain/member/application/MemberService.java
  src/main/java/konkuk/chacall/domain/owner/application/OwnerService.java
  src/main/java/konkuk/chacall/domain/owner/application/myfoodtruckmenu/MyFoodTruckMenuService.java
  src/main/java/konkuk/chacall/domain/owner/presentation/OwnerController.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/request/MyFoodTruckMenuListRequest.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/request/RegisterMenuRequest.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/request/UpdateMenuStatusRequest.java
  src/main/java/konkuk/chacall/domain/owner/presentation/dto/response/MyFoodTruckMenuResponse.java
  src/main/java/konkuk/chacall/domain/user/application/UserService.java
  src/main/java/konkuk/chacall/domain/user/application/admin/AdminService.java
  src/main/java/konkuk/chacall/domain/user/application/validator/AdminValidator.java
  src/main/java/konkuk/chacall/domain/user/domain/model/Role.java
  src/main/java/konkuk/chacall/domain/user/domain/model/User.java
  src/main/java/konkuk/chacall/domain/user/presentation/UserController.java
  src/main/java/konkuk/chacall/domain/user/presentation/dto/request/ApproveFoodTruckStatusRequest.java
  src/main/java/konkuk/chacall/global/common/dto/CursorPagingRequest.java
  src/main/java/konkuk/chacall/global/common/dto/HasPaging.java
  src/main/java/konkuk/chacall/global/common/dto/SortType.java
  src/main/java/konkuk/chacall/global/common/exception/code/ErrorCode.java
  src/main/java/konkuk/chacall/global/common/swagger/SwaggerResponseDescription.java
Labels: 🛠️ feat, ☺️ 상균
